name: Bug Report
description: Report something that isn't working
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
 - type: markdown
   attributes:
     value: |
       Thanks for taking the time to report this issue!
 
 - type: textarea
   id: what-happened
   attributes:
     label: What happened?
     description: A clear description of the bug and what you expected instead
     placeholder: |
       When I tried to...
       I expected...
       But instead...
   validations:
     required: true
 
 - type: textarea
   id: steps
   attributes:
     label: Steps to reproduce
     description: How can we recreate this issue?
     placeholder: |
       1. Go to...
       2. Click on...
       3. See error
     value: |
       1. 
       2. 
       3. 
   validations:
     required: true
 
 - type: input
   id: version
   attributes:
     label: App Version
     description: Found in Settings → About (if applicable)
     placeholder: "e.g., 1.0.0"

 - type: textarea
   id: context
   attributes:
     label: Additional context
     description: Screenshots, error messages, or anything else that might help
     placeholder: Drag and drop images here or paste error messages
